- BOJ/[1759] 암호 만들기/SUbbb/Main.java
- BOJ/[1759] 암호 만들기/SUbbb/README.md
- BOJ/[2529] 부등호/SUbbb/Main.java
- BOJ/[2529] 부등호/SUbbb/README.md
> SUbbb : [1week]

- BOJ/[1759] 암호 만들기/ksg2388/README.md
- BOJ/[1759] 암호 만들기/ksg2388/boj1759.java
- BOJ/[2529] 부등호/ksg2388/README.md
- BOJ/[2529] 부등호/ksg2388/boj2529.java
> Ksg2388 : [1week]

- BOJ/[1759] 암호 만들기/HyeW/MakePassword.java
- BOJ/[1759] 암호 만들기/HyeW/README.md
- BOJ/[2529] 부등호/HyeW/InequalitySign.java
- BOJ/[2529] 부등호/HyeW/README.md
> HyeW : [1week] 

- BOJ/[1759] 암호 만들기/jungu12/Main.java
- BOJ/[1759] 암호 만들기/jungu12/README.md
- BOJ/[2529] 부등호/jungu12/Main.java
- BOJ/[2529] 부등호/jungu12/README.md
> Jungu12 : [1week]

- BOJ/[1759] 암호 만들기/asever0318/README.md
- BOJ/[1759] 암호 만들기/asever0318/Solution_1759.java
- BOJ/[2529] 부등호/asever0318/README.md
- BOJ/[2529] 부등호/asever0318/Solution_2529.java
> asever0318 : [1week]

- BOJ/[1759] 암호 만들기/yeahLim/Main.java
- BOJ/[1759] 암호 만들기/yeahLim/README.md
- BOJ/[2529] 부등호/yeahLim/Main.java
- BOJ/[2529] 부등호/yeahLim/README.md
> yeahLim : [1week]

- BOJ/[11600] 구간 합 구하기 5/ksg2388/Main.java
- BOJ/[11600] 구간 합 구하기 5/ksg2388/README.md
- BOJ/[2206] 벽 부수고 이동하기/ksg2388/Main.java
- BOJ/[2206] 벽 부수고 이동하기/ksg2388/README.md
- BOJ/[7576] 토마토/ksg2388/Main.java
- BOJ/[7576] 토마토/ksg2388/README.md
- SWEA/[1234] 비밀번호/ksg2388/README.md
- SWEA/[1234] 비밀번호/ksg2388/Solution.java
- SWEA/[7465] 창용 마을 무리의 개수/ksg2388/README.md
- SWEA/[7465] 창용 마을 무리의 개수/ksg2388/Solution.java
1.  구간 합 구하기 5
> - 시간 복잡도 : $O(N)$
2.  토마토
> - 시간 복잡도 : $O(N^2)$
3.  벽 부수고 이동하기
> - 시간 복잡도 : $O(N^2)$
4. 비밀번호
> - 시간 복잡도 : $O(N)$
5. 창용 마을 무리의 개수
> - 시간 복잡도 : $O(N^2)$
> ksg2388 : [3week]

- BOJ/[11660] 구간 합 구하기 5/HyeW/README.md
- BOJ/[11660] 구간 합 구하기 5/HyeW/SectionSum5.java
- BOJ/[2206] 벽 부수고 이동하기/HyeW/CrashWallAndMove.java
- BOJ/[2206] 벽 부수고 이동하기/HyeW/README.md
- BOJ/[7576] 토마토/HyeW/README.md
- BOJ/[7576] 토마토/HyeW/Tomato.java
- SWEA/[1234] 비밀번호/HyeW/Password.java
- SWEA/[1234] 비밀번호/HyeW/README.md
- SWEA/[7465] 창용 마을 무리의 개수/HyeW/README.md
- SWEA/[7465] 창용 마을 무리의 개수/HyeW/VillageNumber.java
1. 구간 합 구하기5
- 시간복잡도: $O(N)$
2. 토마토
3. 벽 부수고 이동하기
4. 비밀번호
- 시간복잡도: $O(N)$
5. 창용 마을 무리의 개수
> HyeW : [3week]

- BOJ/[11660] 구간 합 구하기 5/yeahLim/Main.java
- BOJ/[11660] 구간 합 구하기 5/yeahLim/README.md
- BOJ/[2206] 벽 부수고 이동하기/yeahLim/Main.java
- BOJ/[2206] 벽 부수고 이동하기/yeahLim/README.md
- BOJ/[7576] 토마토/yeahLim/Main.java
- BOJ/[7576] 토마토/yeahLim/README.md
- SWEA/[1234] 비밀번호/yeahLim/README.md
- SWEA/[1234] 비밀번호/yeahLim/Solution.java
- SWEA/[7465] 창용 마을 무리의 개수/yeahLim/README.md
- SWEA/[7465] 창용 마을 무리의 개수/yeahLim/Solution.java
1. 구간 합 구하기 5
시간 복잡도 : $O(N^2)$
2. 토마토
시간 복잡도 : $O(NlogN)$
3. 벽 부수고 이동하기
시간 복잡도 :  $O(N^2)$
4. 비밀번호
시간 복잡도 : $O(NlogN)$
5. 창용 마을 무리의 개수
시간 복잡도 : $O(NlogN)$
> yeahLim : [3week]

- BOJ/[16472] 고냥이/asever0318/Main_16472.java
- BOJ/[16472] 고냥이/asever0318/README.md
- BOJ/[17070] 파이프 옮기기 1/asever0318/Main_17070.java
- BOJ/[17070] 파이프 옮기기 1/asever0318/README.md
- BOJ/[17406] 배열 돌리기 4/asever0318/Main_17406.java
- BOJ/[17406] 배열 돌리기 4/asever0318/README.md
- BOJ/[9935] 문자열 폭발/asever0318/Main_9935.java
- BOJ/[9935] 문자열 폭발/asever0318/README.md
- SWEA/[3752] 가능한 시험 점수/asever0318/README.md
- SWEA/[3752] 가능한 시험 점수/asever0318/Solution_3752.java
1. 문자열 폭발
- 시간복잡도 : $O(NlogN)$
2. 고냥이
- 시간복잡도 : $O(NlogN)$
3. 가능한 시험 점수
4. 배열 돌리기 4
5. 파이프 옮기기 1
> asever0318 : [4week]

- BOJ/[12100] 2048 (Easy)/ksg2388/Main.java
- BOJ/[12100] 2048 (Easy)/ksg2388/README.md
- BOJ/[14502] 연구소/ksg2388/Main.java
- BOJ/[14502] 연구소/ksg2388/README.md
- BOJ/[2931] 가스관/ksg2388/Main.java
- BOJ/[2931] 가스관/ksg2388/README.md
- CodeTree/싸움땅/ksg2388/Main.java
- CodeTree/싸움땅/ksg2388/README.md
- SWEA/[2383] 점심 식사시간/ksg2388/README.md
- SWEA/[2383] 점심 식사시간/ksg2388/Solution.java
1. 연구소
2. 가스관
3. 싸움땅
4. 2048 (Easy)
5. 점심 식사시간
> Ksg2388 : 5week

- BOJ/[12100] 2048 (Easy)/HyeW/Easy2048.java
- BOJ/[12100] 2048 (Easy)/HyeW/README.md
- BOJ/[14502] 연구소/HyeW/Laboratory.java
- BOJ/[14502] 연구소/HyeW/README.md
- BOJ/[2931] 가스관/HyeW/GasPipe.java
- BOJ/[2931] 가스관/HyeW/README.md
- CodeTree/싸움땅/HyeW/FightDang.java
- CodeTree/싸움땅/HyeW/README.md
- SWEA/[2383] 점심 식사시간/HyeW/LunchTime.java
- SWEA/[2383] 점심 식사시간/HyeW/README.md
1. 연구소
2. 가스관
3. 싸움땅
4. 2048 (Easy)
5. 점심 식사시간
> HyeW : 5week

- BOJ/[12100] 2048 (Easy)/asever0318/Main_12100.java
- BOJ/[12100] 2048 (Easy)/asever0318/README.md
- BOJ/[14502] 연구소/asever0318/Main_14502.java
- BOJ/[14502] 연구소/asever0318/README.md
- BOJ/[2931] 가스관/asever0318/Main_2931.java
- BOJ/[2931] 가스관/asever0318/README.md
- CodeTree/싸움땅/asever0318/Main_싸움땅.java
- CodeTree/싸움땅/asever0318/README.md
- SWEA/[2383] 점심 식사시간/asever0318/README.md
- SWEA/[2383] 점심 식사시간/asever0318/Solution_2383
1. 연구소
2. 가스관
3. 싸움땅
4. 2048 (Easy)
5. 점심 식사시간
> asever0318 : 5week

- BOJ/[17136] 색종이 붙이기/jungu12/Main.java
- BOJ/[17136] 색종이 붙이기/jungu12/README.md
- BOJ/[17779] 게리맨더링 2/jungu12/Main.java
- BOJ/[17779] 게리맨더링 2/jungu12/README.md
- BOJ/[1890] 점프/jungu12/Main.java
- BOJ/[1890] 점프/jungu12/README.md
- BOJ/[19237] 어른 상어/jungu12/Main.java
- BOJ/[19237] 어른 상어/jungu12/README.md
- BOJ/[2527] 직사각형/jungu12/Main.java
- BOJ/[2527] 직사각형/jungu12/README.md
1. 점프
2. 어른 상어
3. 색종이 붙이기
4. 게리맨더링 2
5. 직사각형
> jungu12 : [6week]

- BOJ/[17136] 색종이 붙이기/HyeW/AttachPaper.java
- BOJ/[17136] 색종이 붙이기/HyeW/README.md
- BOJ/[17779] 게리맨더링 2/HyeW/Gerrymandering2.java
- BOJ/[17779] 게리맨더링 2/HyeW/README.md
- BOJ/[1890] 점프/HyeW/Jump.java
- BOJ/[1890] 점프/HyeW/README.md
- BOJ/[19237] 어른 상어/HyeW/AdultShark.java
- BOJ/[19237] 어른 상어/HyeW/README.md
- BOJ/[2527] 직사각형/HyeW/README.md
- BOJ/[2527] 직사각형/HyeW/Rectangle_Main.java
1. 점프
- 시간복잡도: $O(N)$
2. 어른 상어
3. 색종이 붙이기
4. 게리맨더링2
5. 직사각형
> HyeW : [6week]

- Programmers/[118668] 코딩 테스트 공부/SUbbb/README.md
- Programmers/[118668] 코딩 테스트 공부/SUbbb/Solution.java
- Programmers/[118669] 등산코스 정하기/SUbbb/README.md
- Programmers/[118669] 등산코스 정하기/SUbbb/Solution.java
- Programmers/[131704] 택배상자/SUbbb/README.md
- Programmers/[131704] 택배상자/SUbbb/Solution.java
- Programmers/[17683] 방금그곡/SUbbb/README.md
- Programmers/[17683] 방금그곡/SUbbb/Solution.java
- Programmers/[62048] 멀쩡한 사각형/SUbbb/README.md
- Programmers/[62048] 멀쩡한 사각형/SUbbb/Solution.java
1. 멀쩡한 사각형
2. 택배상자
3. 코딩 테스트 공부
4. 등산코스 정하기
5. 방금 그곡
> SUbbb : [7week]

- Programmers/[118668] 코딩 테스트 공부/jungu12/README.md
- Programmers/[118668] 코딩 테스트 공부/jungu12/Solution.java
- Programmers/[118669] 등산코스 정하기/jungu12/README.md
- Programmers/[118669] 등산코스 정하기/jungu12/Solution.java
- Programmers/[131704] 택배상자/jungu12/README.md
- Programmers/[131704] 택배상자/jungu12/Solution.java
- Programmers/[17683] 방금그곡/jungu12/README.md
- Programmers/[17683] 방금그곡/jungu12/Solution.java
- Programmers/[62048] 멀쩡한 사각형/jungu12/README.md
- Programmers/[62048] 멀쩡한 사각형/jungu12/Solution.java
1. 멀쩡한 사각형
2. 택배상자
3. 코딩 테스트 공부
4. 등산코스 정하기
- 시간 복잡도 : $O(N(logN))$
5. 방금 그곡
> jungu12 : [7week]

- Programmers/[118668] 코딩 테스트 공부/ksg2388/README.md
- Programmers/[118668] 코딩 테스트 공부/ksg2388/Solution.java
- Programmers/[118669] 등산코스 정하기/ksg2388/README.md
- Programmers/[118669] 등산코스 정하기/ksg2388/Solution.java
- Programmers/[131704] 택배상자/ksg2388/README.md
- Programmers/[131704] 택배상자/ksg2388/Soultion.java
- Programmers/[17683] 방금그곡/ksg2388/README.md
- Programmers/[17683] 방금그곡/ksg2388/Solution.java
- Programmers/[62048] 멀쩡한 사각형/ksg2388/README.md
- Programmers/[62048] 멀쩡한 사각형/ksg2388/Soultion.java
1. 멀쩡한 사각형
2. 택배상자
3. 코딩 테스트 공부
4. 등산코스 정하기
5. 방금 그곡
> Ksg2388 : [7week]

- BOJ/[14891] 톱니바퀴/HyeW/Gear.java
- BOJ/[14891] 톱니바퀴/HyeW/README.md
- CodeTree/코드트리 빵/HyeW/CodeTreeBread.java
- CodeTree/코드트리 빵/HyeW/README.md
- Programmers/[148653] 마법의 엘리베이터/HyeW/README.md
- Programmers/[148653] 마법의 엘리베이터/Solution.java
- Programmers/[150367] 표현 가능한 이진트리/HyeW/README.md
- Programmers/[150367] 표현 가능한 이진트리/HyeW/Solution.java
- Programmers/[159993] 미로 탈출/HyeW/README.md
- Programmers/[159993] 미로 탈출/HyeW/Solution.java
1. 마법의 엘리베이터
2. 미로 탈출
3. 표현 가능한 이진트리
- 시간복잡도 : $O(logN)$
5. 톱니바퀴
6. 코드트리 빵
> HyeW : [8week]

- BOJ/[14891] 톱니바퀴/asever0318/Main_14891.java
- BOJ/[14891] 톱니바퀴/asever0318/README.md
- CodeTree/코드트리 빵/asever0318/README.md
- CodeTree/코드트리 빵/asever0318/Solution_코드트리빵.java
- Programmers/[148653] 마법의 엘리베이터/asever0318/README.md
- Programmers/[148653] 마법의 엘리베이터/asever0318/Solution_148653.java
- Programmers/[150367] 표현 가능한 이진트리/asever0318/README.md
- Programmers/[150367] 표현 가능한 이진트리/asever0318/Solution_150367.java
- Programmers/[159993] 미로 탈출/asever0318/README.md
- Programmers/[159993] 미로 탈출/asever0318/Solution_159993.java
1. 마법의 엘리베이터
2. 미로 탈출
3. 표현 가능한 이진트리
- 시간 복잡도 : $O(Nlog(N)$
4. 톱니바퀴
5. 코드트리 빵
> asever0318 : [8week]

- BOJ/[14891] 톱니바퀴/SUbbb/Main.java
- BOJ/[14891] 톱니바퀴/SUbbb/README.md
- CodeTree/코드트리 빵/SUbbb/Main.java
- CodeTree/코드트리 빵/SUbbb/README.md
- Programmers/[148653] 마법의 엘리베이터/SUbbb/README.md
- Programmers/[148653] 마법의 엘리베이터/SUbbb/Solution.java
- Programmers/[150367] 표현 가능한 이진트리/SUbbb/README.md
- Programmers/[150367] 표현 가능한 이진트리/SUbbb/Solution.java
- Programmers/[159993] 미로 탈출/SUbbb/README.md
- Programmers/[159993] 미로 탈출/SUbbb/Solution.java
1. 마법의 엘리베이터
2. 미로 탈출
3. 표현 가능한 이진트리
4. 톱니바퀴
5. 코드트리 빵
> SUbbb : [8week]

- CodeTree/꼬리잡기놀이/asever0318/Main_꼬리잡기놀이.java
- CodeTree/꼬리잡기놀이/asever0318/README.md
> asever0318 : [9week]

- BOJ/[1167] 트리의 지름/jungu12/Main.java
- BOJ/[1167] 트리의 지름/jungu12/README.md
- BOJ/[16928] 뱀과 사다리 게임/jungu12/Main.java
- BOJ/[16928] 뱀과 사다리 게임/jungu12/README.md
- BOJ/[17144] 미세먼지 안녕!/jungu12/Main.java
- BOJ/[17144] 미세먼지 안녕!/jungu12/README.md
- BOJ/[1932] 정수 삼각형/jungu12/Main.java
- BOJ/[1932] 정수 삼각형/jungu12/README.md
- CodeTree/팩맨/jungu12/Main.java
- CodeTree/팩맨/jungu12/README.md
1. 정수 삼각형
2. 뱀과 사다리 게임
3. 트리의 지름
4. 미세먼지 안녕!
5. 팩맨
> jungu12 : [10week]

- BOJ/[1167] 트리의 지름/SUbbb/Main.java
- BOJ/[1167] 트리의 지름/SUbbb/README.md
- BOJ/[16928] 뱀과 사다리 게임/SUbbb/Main.java
- BOJ/[16928] 뱀과 사다리 게임/SUbbb/README.md
- BOJ/[17144] 미세먼지 안녕!/SUbbb/Main.java
- BOJ/[17144] 미세먼지 안녕!/SUbbb/README.md
- BOJ/[1932] 정수 삼각형/SUbbb/Main.java
- BOJ/[1932] 정수 삼각형/SUbbb/README.md
- CodeTree/팩맨/SUbbb/Main.java
- CodeTree/팩맨/SUbbb/README.md
1. 정수 삼각형
2. 뱀과 사다리 게임
3. 트리의 지름
4. 미세먼지 안녕!
5. 팩맨
> SUbbb : [10week]

- BOJ/[1167] 트리의 지름/ksg2388/Main.java
- BOJ/[1167] 트리의 지름/ksg2388/README.md
- BOJ/[16928] 뱀과 사다리 게임/ksg2388/Main.java
- BOJ/[16928] 뱀과 사다리 게임/ksg2388/README.md
- BOJ/[17144] 미세먼지 안녕!/ksg2388/Main.java
- BOJ/[17144] 미세먼지 안녕!/ksg2388/README.md
- BOJ/[1932] 정수 삼각형/ksg2388/Main.java
- BOJ/[1932] 정수 삼각형/ksg2388/README.md
- CodeTree/팩맨/ksg2388/README.md
- CodeTree/팩맨/ksg2388/Solution.java
1. 정수 삼각형
2. 뱀과 사다리 게임
3. 트리의 지름
4. 미세먼지 안녕!
5. 팩맨
> Ksg2388 : [10week]

- BOJ/[1167] 트리의 지름/HyeW/Main.java
- BOJ/[1167] 트리의 지름/HyeW/README.md
- BOJ/[16928] 뱀과 사다리 게임/HyeW/Main.java
- BOJ/[16928] 뱀과 사다리 게임/HyeW/README.md
- BOJ/[17144] 미세먼지 안녕!/HyeW/Main.java
- BOJ/[17144] 미세먼지 안녕!/HyeW/README.md
- BOJ/[1932] 정수 삼각형/HyeW/Main.java
- BOJ/[1932] 정수 삼각형/HyeW/README.md
- CodeTree/팩맨/HyeW/README.md
- CodeTree/팩맨/HyeW/Solution.java
1. 정수 삼각형
2. 뱀과 사다리 게임
3. 트리의 지름
4. 미세먼지 안녕!
- 시간복잡도 : $O(TNM)$ (T : 시간, N : 가로, M : 세로)
5. 팩맨
- 시간복잡도 : $O(TN^2)$ (T : 시간)
> HyeW : [10week]

- BOJ/[16236] 아기 상어/SUbbb/Main.java
- BOJ/[16236] 아기 상어/SUbbb/README.md
- BOJ/[1865] 웜홀/SUbbb/Main.java
- BOJ/[1865] 웜홀/SUbbb/README.md
- BOJ/[2263] 트리의 순회/SUbbb/Main.java
- BOJ/[2263] 트리의 순회/SUbbb/README.md
- BOJ/[9019] DSLR/SUbbb/Main.java
- BOJ/[9019] DSLR/SUbbb/README.md
- Programmers/[49994] 방문 길이/SUbbb/README.md
- Programmers/[49994] 방문 길이/SUbbb/Solution.java
1. 아기 상어
2. DSLR
3. 트리의 순회
4. 웜홀
5. 방문 길이
> SUbbb : [11week]

- BOJ/[16236] 아기 상어/jungu12/Main.java
- BOJ/[16236] 아기 상어/jungu12/README.md
- BOJ/[1865] 웜홀/jungu12/Main.java
- BOJ/[1865] 웜홀/jungu12/README.md
- BOJ/[2263] 트리의 순회/jungu12/Main.java
- BOJ/[2263] 트리의 순회/jungu12/README.md
- BOJ/[9019] DSLR/jungu12/Main.java
- BOJ/[9019] DSLR/jungu12/README.md
- Programmers/[49994] 방문 길이/jungu12/README.md
- Programmers/[49994] 방문 길이/jungu12/Solution.java
1. 아기 상어
2. DSLR
3. 트리의 순회
4. 웜홀
5. 방문 길이
> jungu12 : [11week]

- BOJ/[16236] 아기 상어/HyeW/Main.java
- BOJ/[16236] 아기 상어/HyeW/README.md
- BOJ/[1865] 웜홀/HyeW/Main.java
- BOJ/[1865] 웜홀/HyeW/README.md
- BOJ/[2263] 트리의 순회/HyeW/README.md
- BOJ/[9019] DSLR/HyeW/Main.java
- BOJ/[9019] DSLR/HyeW/README.md
- Programmers/[49994] 방문 길이/HyeW/README.md
- Programmers/[49994] 방문 길이/HyeW/Solution.java
1. 아기 상어
- 시간복잡도 : $O()$
2. DSLR
3. 트리의 순회
4. 웜홀
- 시간 복잡도 : $O(N^3)$
5. 방문 길이
> HyeW : [11week]

- BOJ/[16236] 아기 상어/asever0318/Main_16236.java
- BOJ/[16236] 아기 상어/asever0318/README.md
- BOJ/[1865] 웜홀/asever0318/Main_1865.java
- BOJ/[1865] 웜홀/asever0318/README.md
- BOJ/[2263] 트리의 순회/asever0318/Main_2263.java
- BOJ/[2263] 트리의 순회/asever0318/README.md
- BOJ/[9019] DSLR/asever0318/Main_9019.java
- BOJ/[9019] DSLR/asever0318/README.md
- Programmers/[49994] 방문 길이/asever0318/README.md
- Programmers/[49994] 방문 길이/asever0318/Solution_49994.java
1. 아기 상어
2. DSLR
3. 트리의 순회
4. 웜홀
5. 방문 길이
> asever0318 : [11week]

- BOJ/[11279] 최대 힙/HyeW/Main.java
- BOJ/[11279] 최대 힙/HyeW/README.md
- BOJ/[11726] 2xn 타일링/HyeW/Main.java
- BOJ/[11726] 2xn 타일링/HyeW/README.md
- BOJ/[13549] 숨바꼭질 3/HyeW/Main.java
- BOJ/[13549] 숨바꼭질 3/HyeW/README.md
- BOJ/[1918] 후위 표기식/HyeW/Main.java
- BOJ/[1918] 후위 표기식/HyeW/README.md
- Programmers/[92342] 양궁대회/HyeW/README.md
- Programmers/[92342] 양궁대회/HyeW/Solution.java
1. 2xn 타일링
2. 최대 힙
3. 숨바꼭질 3
4. 후위 표기식
5. 양궁 대회
- 시간 복잡도 : $O(N! / (R! * (N - R)!))$  (N개 중 R개를 뽑을 경우)
> HyeW : [12week]

- BOJ/[11279] 최대 힙/SUbbb/Main.java
- BOJ/[11279] 최대 힙/SUbbb/README.md
- BOJ/[11726] 2xn 타일링/SUbbb/Main.java
- BOJ/[11726] 2xn 타일링/SUbbb/README.md
- BOJ/[13549] 숨바꼭질 3/SUbbb/Main.java
- BOJ/[13549] 숨바꼭질 3/SUbbb/README.md
- BOJ/[1918] 후위 표기식/SUbbb/Main.java
- BOJ/[1918] 후위 표기식/SUbbb/README.md
- Programmers/[92342] 양궁대회/SUbbb/README.md
- Programmers/[92342] 양궁대회/SUbbb/Solution.java
1. 2xn 타일링
2. 최대 힙
3. 숨바꼭질 3
4. 후위 표기식
5. 양궁 대회
> SUbbb : [12week]

- BOJ/[11279] 최대 힙/ksg2388/Main.js
- BOJ/[11279] 최대 힙/ksg2388/README.md
- BOJ/[11726] 2×n 타일링/ksg2388/Main.js
- BOJ/[11726] 2×n 타일링/ksg2388/README.md
- BOJ/[13549] 숨바꼭질 3/ksg2388/Main.js
- BOJ/[13549] 숨바꼭질 3/ksg2388/README.md
- BOJ/[1918] 후위 표기식/ksg2388/Main.js
- BOJ/[1918] 후위 표기식/ksg2388/README.md
- Programmers/[92342] 양궁대회/ksg2388/README.md
- Programmers/[92342] 양궁대회/ksg2388/Solution.js
1. 2xn 타일링
2. 최대 힙
3. 숨바꼭질 3
4. 후위 표기식
5. 양궁 대회
> Ksg2388 : [12week]

- BOJ/[11279] 최대 힙/jungu12/Main.java
- BOJ/[11279] 최대 힙/jungu12/README.md
- BOJ/[11726] 2xn 타일링/jungu12/Main.java
- BOJ/[11726] 2xn 타일링/jungu12/README.md
- BOJ/[13549] 숨바꼭질 3/jungu12/Main.java
- BOJ/[13549] 숨바꼭질 3/jungu12/README.md
- BOJ/[1918] 후위 표기식/jungu12/Main.java
- BOJ/[1918] 후위 표기식/jungu12/README.md
- Programmers/[92342] 양궁대회/jungu12/README.md
- Programmers/[92342] 양궁대회/jungu12/Solution.java
1. 2xn 타일링
2. 최대 힙
3. 숨바꼭질 3
4. 후위 표기식
5. 양궁 대회
- 시간 복잡도 : $O(2^N)$
> jungu12 : [12week]

- Programmers/[92342] 양궁대회/asever0318/README.md
- Programmers/[92342] 양궁대회/asever0318/Solution_92342.java
1. 2xn 타일링
2. 최대 힙
3. 숨바꼭질 3
4. 후위 표기식
5. 양궁 대회
- 시간 복잡도 : $O(N^r)$
> asever0318 : [12week]

- BOJ/[11276] 2xn 타일링/yeahLim/Main.java
- BOJ/[11276] 2xn 타일링/yeahLim/README.md
- BOJ/[11279] 최대 힙/yeahLim/Main.java
- BOJ/[11279] 최대 힙/yeahLim/README.md
- BOJ/[13549] 숨바꼭질 3/yeahLim/Main.java
- BOJ/[13549] 숨바꼭질 3/yeahLim/README.md
- BOJ/[1918] 후위 표기식/yeahLim/Main.java
- BOJ/[1918] 후위 표기식/yeahLim/README.md
1. 2xn 타일링
2. 최대 힙
3. 숨바꼭질 3
- 시간 복잡도 : $O(V+E)$
4. 후위 표기식
5. 양궁 대회
- 시간 복잡도 : $O()$
> yeahLim : [12week]

- Programmers/[12913] 땅따먹기/asever0318/README.md
- Programmers/[12913] 땅따먹기/asever0318/Solution_12913.java
- Programmers/[12938] 최고의 집합/asever0318/README.md
- Programmers/[12938] 최고의 집합/asever0318/Solution_12938.java
- Programmers/[150369] 택배 배달과 수거하기/asever0318/README.md
- Programmers/[150369] 택배 배달과 수거하기/asever0318/Solution_150369.java
- Programmers/[42860] 조이스틱/asever0318/README.md
- Programmers/[42860] 조이스틱/asever0318/Solution_42860.java
- Programmers/[92341] 주차 요금 관리/asever0318/README.md
- Programmers/[92341] 주차 요금 관리/asever0318/Solution_92341.java
1. 최고의 집합
- 시간 복잡도: $O(N)$
2. 땅따먹기
3. 주차 요금 계산
- 시간 복잡도: $O(N)$
4. 조이스틱
5. 택배 배달과 수거하기
> asever0318 : [13week]

- Programmers/[12913] 땅따먹기/ksg2388/README.md
- Programmers/[12913] 땅따먹기/ksg2388/Solution.js
- Programmers/[12938] 최고의 집합/ksg2388/README.md
- Programmers/[12938] 최고의 집합/ksg2388/Solution.js
- Programmers/[150369] 택배 배달과 수거하기/ksg2388/README.md
- Programmers/[150369] 택배 배달과 수거하기/ksg2388/Solution.js
- Programmers/[42860] 조이스틱/ksg2388/README.md
- Programmers/[42860] 조이스틱/ksg2388/Solution.js
- Programmers/[92341] 주차 요금 계산/ksg2388/README.md
- Programmers/[92341] 주차 요금 계산/ksg2388/Solution.js
1. 최고의 집합
- 시간 복잡도: $O(N)$
2. 땅따먹기
3. 주차 요금 계산
4. 조이스틱
5. 택배 배달과 수거하기
> Ksg2388 : [13week]

- Programmers/[12913] 땅따먹기/jungu12/README.md
- Programmers/[12913] 땅따먹기/jungu12/Solution.java
- Programmers/[12938] 최고의 집합/jungu12/README.md
- Programmers/[12938] 최고의 집합/jungu12/Solution.java
- Programmers/[150369] 택배 배달과 수거하기/jungu12/README.md
- Programmers/[150369] 택배 배달과 수거하기/jungu12/Solution.java
- Programmers/[42860] 조이스틱/jungu12/README.md
- Programmers/[42860] 조이스틱/jungu12/Solution.java
- Programmers/[92341] 주차 요금 계산/jungu12/README.md
- Programmers/[92341] 주차 요금 계산/jungu12/Solution.java
1. 최고의 집합
- 시간 복잡도: $O(N)$
2. 땅따먹기
3. 주차 요금 계산
4. 조이스틱
5. 택배 배달과 수거하기
> Jungu12 : [13week]

- Programmers/[131130] 혼자 놀기의 달인/asever0318/README.md
- Programmers/[131130] 혼자 놀기의 달인/asever0318/Solution_131130.java
- Programmers/[160585] 혼자서 하는 틱택토/asever0318/README.md
- Programmers/[160585] 혼자서 하는 틱택토/asever0318/Solution_160585.java
- Programmers/[161988] 연속 펄스 부분 수열의 합/asever0318/README.md
- Programmers/[161988] 연속 펄스 부분 수열의 합/asever0318/Solution_161988.java
- Programmers/[172927] 광물 캐기/asever0318/README.md
- Programmers/[172927] 광물 캐기/asever0318/Solution_172927.java
- Programmers/[77485] 행렬 테두리 회전하기/asever0318/README.md
- Programmers/[77485] 행렬 테두리 회전하기/asever0318/Solution_77485.java
1. 혼자서 하는 틱택토
2. 혼자 놀기의 달인
3. 광물 캐기
4. 행렬 테두리 회전하기
5. 연속 펄스 부분 수열의 합
- 시간 복잡도: $O(N)$
> asever0318 : [14week]

- Programmers/[131130] 혼자 놀기의 달인/SUbbb/README.md
- Programmers/[131130] 혼자 놀기의 달인/SUbbb/Solution.java
- Programmers/[160585] 혼자서 하는 틱택토/SUbbb/README.md
- Programmers/[160585] 혼자서 하는 틱택토/SUbbb/Solution.java
- Programmers/[172927] 광물 캐기/SUbbb/README.md
- Programmers/[172927] 광물 캐기/SUbbb/Solution.java
- Programmers/[77485] 행렬 테두리 회전하기/SUbbb/README.md
- Programmers/[77485] 행렬 테두리 회전하기/SUbbb/Solution.java
1. 혼자서 하는 틱택토
2. 혼자 놀기의 달인
3. 광물 캐기
4. 행렬 테두리 회전하기
> SUbbb : [14week]

- Programmers/[131130] 혼자 놀기의 달인/ksg2388/README.md
- Programmers/[131130] 혼자 놀기의 달인/ksg2388/Solution.js
- Programmers/[160585] 혼자서 하는 틱택토/ksg2388/README.md
- Programmers/[160585] 혼자서 하는 틱택토/ksg2388/Solution.js
- Programmers/[161988] 연속 펄스 부분 수열의 합/README.md
- Programmers/[161988] 연속 펄스 부분 수열의 합/Solution.js
- Programmers/[172927] 광물 캐기/ksg2388/README.md
- Programmers/[172927] 광물 캐기/ksg2388/Solution.js
- Programmers/[77485] 행렬 테두리 회전하기/ksg2388/README.md
- Programmers/[77485] 행렬 테두리 회전하기/ksg2388/Solution.js
1. 혼자서 하는 틱택토
2. 혼자 놀기의 달인
3. 광물 캐기
4. 행렬 테두리 회전하기
5. 연속 펄스 부분 수열의 합
> Ksg2388 : [14week]

- Programmers/[142085] 디펜스 게임/jungu12/README.md
- Programmers/[142085] 디펜스 게임/jungu12/Solution.java
- Programmers/[152995] 인사고과/jungu12/README.md
- Programmers/[152995] 인사고과/jungu12/Solution.java
- Programmers/[169199] 리코쳇 로봇/jungu12/README.md
- Programmers/[169199] 리코쳇 로봇/jungu12/Solution.java
- Programmers/[181188] 요격 시스템/jungu12/README.md
- Programmers/[181188] 요격 시스템/jungu12/Solution.java
- Programmers/[67259] 경주로 건설/jungu12/README.md
- Programmers/[67259] 경주로 건설/jungu12/Solution.java
1. 디펜스 게임
2. 리코쳇 로봇
3. 요격 시스템
- 시간복잡도 : $O(NlogN)$
4. 인사고과
5. 경주로 건설
> Jungu12 : [15week]

- Programmers/[142085] 디펜스 게임/ksg2388/README.md
- Programmers/[142085] 디펜스 게임/ksg2388/Solution.js
- Programmers/[152995] 인사고과/ksg2388/README.md
- Programmers/[152995] 인사고과/ksg2388/Solution.js
- Programmers/[169199] 리코쳇 로봇/ksg2388/README.md
- Programmers/[169199] 리코쳇 로봇/ksg2388/Solution.js
- Programmers/[181188] 요격 시스템/ksg2388/README.md
- Programmers/[181188] 요격 시스템/ksg2388/Solution.js
- Programmers/[67259] 경주로 건설/ksg2388/README.md
- Programmers/[67259] 경주로 건설/ksg2388/Solution.js
1. 디펜스 게임
2. 리코쳇 로봇
3. 요격 시스템
4. 인사고과
5. 경주로 건설
> Ksg2388 : [15week]

- Programmers/[142085] 디펜스 게임/yeahLim/README.md
- Programmers/[142085] 디펜스 게임/yeahLim/Solution.java
- Programmers/[152995] 인사고과/yeahLim/README.md
- Programmers/[152995] 인사고과/yeahLim/Solution.java
- Programmers/[169199] 리코쳇 로봇/yeahLim/README.md
- Programmers/[169199] 리코쳇 로봇/yeahLim/Solution.java
- Programmers/[181188] 요격 시스템/yeahLim/README.md
- Programmers/[181188] 요격 시스템/yeahLim/Solution.java
- Programmers/[67259] 경주로 건설/yeahLim/README.md
- Programmers/[67259] 경주로 건설/yeahLim/Solution.java
1. 디펜스 게임
2. 리코쳇 로봇
3. 요격 시스템
- 시간복잡도 : $O(NlogN)$
4. 인사고과
- 시간복잡도 : $O(NlogN)$
5. 경주로 건설
> yeahLim : [15week]

- BOJ/[10282] 해킹/jungu12/Main.java
- BOJ/[10282] 해킹/jungu12/README.md
- BOJ/[16724] 피리 부는 사나이/jungu12/Main.java
- BOJ/[16724] 피리 부는 사나이/jungu12/README.md
- BOJ/[17404] RGB거리 2/jungu12/Main.java
- BOJ/[17404] RGB거리 2/jungu12/README.md
- BOJ/[2056] 작업/jungu12/Main.java
- BOJ/[2056] 작업/jungu12/README.md
- BOJ/[3020] 개똥벌레/jungu12/Main.java
- BOJ/[3020] 개똥벌레/jungu12/README.md
1. 피리 부는 사나이
2. RGB거리 2
3. 개똥벌레
4. 해킹
5. 작업
> jungu12 : [16week]

- BOJ/[10282] 해킹/SUbbb/Main.java
- BOJ/[10282] 해킹/SUbbb/README.md
- BOJ/[16724] 피리 부는 사나이/SUbbb/Main.java
- BOJ/[16724] 피리 부는 사나이/SUbbb/README.md
- BOJ/[17404] RGB거리 2/SUbbb/Main.java
- BOJ/[17404] RGB거리 2/SUbbb/README.md
- BOJ/[2056] 작업/SUbbb/Main.java
- BOJ/[2056] 작업/SUbbb/README.md
- BOJ/[3020] 개똥벌레/SUbbb/Main.java
- BOJ/[3020] 개똥벌레/SUbbb/README.md
1. 피리 부는 사나이
2. RGB거리 2
3. 개똥벌레
4. 해킹
5. 작업
> SUbbb : [16week]

- BOJ/[10282] 해킹/yeahLim/Main.java
- BOJ/[10282] 해킹/yeahLim/README.md
- BOJ/[16724] 피리 부는 사나이/yeahLim/Main.java
- BOJ/[16724] 피리 부는 사나이/yeahLim/README.md
- BOJ/[17404] RGB거리 2/yeahLim/Main.java
- BOJ/[17404] RGB거리 2/yeahLim/README.md
- BOJ/[3020] 개똥벌레/yeahLim/Main.java
- BOJ/[3020] 개똥벌레/yeahLim/README.md
1. 피리 부는 사나이
2. RGB거리 2
3. 개똥벌레
- 시간 복잡도 : $O(n + h)$
4. 해킹
- 시간 복잡도 : $O((n + d) log n)$
5. 작업
> yeahLim : [16week]

- BOJ/[1238] 파티/asever0318/Main_1238.java
- BOJ/[1238] 파티/asever0318/README.md
- BOJ/[2156] 포도주 시식/asever0318/Main_2156.java
- BOJ/[2156] 포도주 시식/asever0318/README.md
> asever0318 : [17week]

- BOJ/[11444] 피보나치 수 6/HyeW/Main.java
- BOJ/[11444] 피보나치 수 6/HyeW/README.md
- BOJ/[1238] 파티/HyeW/Main.java
- BOJ/[1238] 파티/HyeW/README.md
- BOJ/[14676] 영우는 사기꾼?/HyeW/Main.java
- BOJ/[14676] 영우는 사기꾼?/HyeW/README.md
- BOJ/[16946] 벽 부수고 이동하기 4/HyeW/Main.java
- BOJ/[16946] 벽 부수고 이동하기 4/HyeW/README.md
- BOJ/[2156] 포도주 시식/HyeW/Main.java
- BOJ/[2156] 포도주 시식/HyeW/README.md
1. 포도주 시식
2. 벽 부수고 이동하기 4
- 수정 전
- 수정 후
3. 파티
4. 피보나치 수 6
5. 영우는 사기꾼?
> HyeW : [17week]

- BOJ/[11444] 피보나치 수 6/yeahLim/Main.java
- BOJ/[11444] 피보나치 수 6/yeahLim/README.md
- BOJ/[1238] 파티/yeahLim/Main.java
- BOJ/[1238] 파티/yeahLim/README.md
- BOJ/[14676] 영우는 사기꾼 ?/yeahLim/Main.java
- BOJ/[14676] 영우는 사기꾼 ?/yeahLim/README.md
- BOJ/[16946] 벽 부수고 이동하기 4/yeahLim/Main.java
- BOJ/[16946] 벽 부수고 이동하기 4/yeahLim/README.md
- BOJ/[2156] 포도주 시식/yeahLim/Main.java
- BOJ/[2156] 포도주 시식/yeahLim/README.md
1. 포도주 시식
2. 벽 부수고 이동하기 4
3. 파티
4. 피보나치 수 6
5. 영우는 사기꾼?
> YeahLim : [17week]

- BOJ/[11444] 피보나치 수 6/ksg2388/Main.js
- BOJ/[11444] 피보나치 수 6/ksg2388/README.md
- BOJ/[1238] 파티/ksg2388/Main.js
- BOJ/[1238] 파티/ksg2388/README.md
- BOJ/[14676] 영우는 사기꾼?/ksg2388/Main.js
- BOJ/[14676] 영우는 사기꾼?/ksg2388/README.md
- BOJ/[16946] 벽 부수고 이동하기 4/ksg2388/Main.js
- BOJ/[16946] 벽 부수고 이동하기 4/ksg2388/README.md
- BOJ/[2156] 포도주 시식/ksg2388/Main.js
- BOJ/[2156] 포도주 시식/ksg2388/README.md
1. 포도주 시식
2. 벽 부수고 이동하기 4
3. 파티
4. 피보나치 수 6
5. 영우는 사기꾼?
> Ksg2388: [17week]

- BOJ/[11444] 피보나치 수 6/jungu12/Main.java
- BOJ/[11444] 피보나치 수 6/jungu12/README.md
- BOJ/[1238] 파티/jungu12/Main.java
- BOJ/[1238] 파티/jungu12/README.md
- BOJ/[14676] 영우는 사기꾼?/jungu12/Main.java
- BOJ/[14676] 영우는 사기꾼?/jungu12/README.md
- BOJ/[16946] 벽 부수고 이동하기 4/jungu12/Main.java
- BOJ/[16946] 벽 부수고 이동하기 4/jungu12/README.md
- BOJ/[2156] 포도주 시식/jungu12/Main.java
- BOJ/[2156] 포도주 시식/jungu12/README.md
1. 포도주 시식
2. 벽 부수고 이동하기 4
3. 파티
4. 피보나치 수 6
5. 영우는 사기꾼?
> jungu12 : [17week]

- BOJ/[20166] 문자열 지옥에 빠진 호석/jungu12/Main.java
- BOJ/[20166] 문자열 지옥에 빠진 호석/jungu12/README.md
- BOJ/[20168] 골목 대장 호석 - 기능성/jungu12/Main.java
- BOJ/[20168] 골목 대장 호석 - 기능성/jungu12/README.md
- Programmers/[150366] 표 병합/jungu12/README.md
- Programmers/[150366] 표 병합/jungu12/Solution.java
- Programmers/[154540] 무인도 여행/jungu12/README.md
- Programmers/[154540] 무인도 여행/jungu12/Solution.java
- Programmers/[42584] 주식가격/jungu12/README.md
- Programmers/[42584] 주식가격/jungu12/Solution.java
1. 주식가격
2. 무인도 여행
3. 표 병합
4. 골목 대장 호석 - 기능성
5. 문자열 지옥에 빠진 호석
> Jungu12 : [18week]

- BOJ/[20166] 문자열 지옥에 빠진 호석/SUbbb/Main.java
- BOJ/[20166] 문자열 지옥에 빠진 호석/SUbbb/README.md
- BOJ/[20168] 골목 대장 호석 - 기능성/SUbbb/Main.java
- BOJ/[20168] 골목 대장 호석 - 기능성/SUbbb/README.md
- Programmers/[150366] 표 병합/SUbbb/README.md
- Programmers/[150366] 표 병합/SUbbb/Solution.java
- Programmers/[154540] 무인도 여행/SUbbb/README.md
- Programmers/[154540] 무인도 여행/SUbbb/Solution.java
- Programmers/[42584] 주식가격/SUbbb/README.md
- Programmers/[42584] 주식가격/SUbbb/Solution.java
1. 주식가격
2. 무인도 여행
3. 표 병합
4. 골목 대장 호석 - 기능성
5. 문자열 지옥에 빠진 호석
> SUbbb : [18week]

- BOJ/[20166] 문자열 지옥에 빠진 호석/asever0318/Main_20166.java
- BOJ/[20166] 문자열 지옥에 빠진 호석/asever0318/README.md
- BOJ/[20168] 골목 대장 호석 - 기능성/asever0318/Main_20168.java
- BOJ/[20168] 골목 대장 호석 - 기능성/asever0318/README.md
- Programmers/[154540] 무인도 여행/asever0318/README.md
- Programmers/[154540] 무인도 여행/asever0318/Solution_154540.java
- Programmers/[42584] 주식가격/asever0318/README.md
- Programmers/[42584] 주식가격/asever0318/Solution_42584.java
1. 주식가격
2. 무인도 여행
4. 골목 대장 호석 - 기능성
5. 문자열 지옥에 빠진 호석
> asever0318 : [18week]

- BOJ/[20166] 문자열 지옥에 빠진 호석/yeahLim/Main.java
- BOJ/[20166] 문자열 지옥에 빠진 호석/yeahLim/README.md
- BOJ/[20168] 골목 대장 호석 - 기능성/yeahLim/Main.java
- BOJ/[20168] 골목 대장 호석 - 기능성/yeahLim/README.md
- Programmers/[154540] 무인도 여행/yeahLim/README.md
- Programmers/[154540] 무인도 여행/yeahLim/Solution.java
- Programmers/[42584] 주식가격/yeahLim/README.md
- Programmers/[42584] 주식가격/yeahLim/Solution.java
1. 주식가격
2. 무인도 여행
3. 표 병합
4. 골목 대장 호석 - 기능성
5. 문자열 지옥에 빠진 호석
> Yeah'Lim : [18week]

- BOJ/[15565] 귀여운 라이언/jungu12/Main.java
- BOJ/[15565] 귀여운 라이언/jungu12/README.md
- BOJ/[1563] 개근상/jungu12/Main.java
- BOJ/[1563] 개근상/jungu12/README.md
- BOJ/[3584] 가장 가까운 공통 조상/jungu12/Main.java
- BOJ/[3584] 가장 가까운 공통 조상/jungu12/README.md
- Programmers/[155651] 호텔 대실/jungu12/README.md
- Programmers/[155651] 호텔 대실/jungu12/Solution.java
- Programmers/[68646] 풍선 터트리기/jungu12/README.md
- Programmers/[68646] 풍선 터트리기/jungu12/Solution.java
1. 귀여운 라이언
2. 가장 가까운 공통 조상
3. 개근상
4. 풍선 터트리기
5. 호텔 대실
> jungu12 : [19week]
